# Config file for automatic testing at travis-ci.org

branches:
 only:
  - master

language: python

matrix:
  include:
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.7.0

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.6.5

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.5.5

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=2.7.15

cache:
  directories:
    - $HOME/.pyenv/versions/3.7.0
    - $HOME/.pyenv/versions/3.6.5
    - $HOME/.pyenv/versions/3.5.5
    - $HOME/.pyenv/versions/3.4.8
    - $HOME/.pyenv/versions/2.7.15
    - $HOME/downloads

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir $HOME/bin; ln -s $(which pip2) $HOME/bin/pip; ln -s $(which python2) $HOME/bin/python; fi
  - python -m pip install --disable-pip-version-check --upgrade pip
  - pip install -U scikit-ci scikit-ci-addons
  - ci_addons --install ../addons

install:
  - ci install

script:
  - ci test

after_success:
  - ci after_test
