branches:
 only:
  - master

version: "0.0.1.{build}"

environment:
  matrix:

    # Visual Studio (Python 2 & 3, 32 & 64 bit)
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON_DIR: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"
      BLOCK: "0"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON_DIR: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"
      BLOCK: "0"
      # Used in 'test_platform_windows_find_visual_studio'
      # See https://www.appveyor.com/docs/windows-images-software/#visual-studio-2008
      SKBUILD_TEST_FIND_VS2008_INSTALLATION_EXPECTED: "0"
      SKBUILD_TEST_FIND_VS2010_INSTALLATION_EXPECTED: "1"
      SKBUILD_TEST_FIND_VS2012_INSTALLATION_EXPECTED: "1"
      SKBUILD_TEST_FIND_VS2013_INSTALLATION_EXPECTED: "1"
      SKBUILD_TEST_FIND_VS2015_INSTALLATION_EXPECTED: "1"
      SKBUILD_TEST_FIND_VS2017_INSTALLATION_EXPECTED: "0"

# Disabled due to appveyor timeout
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#      PYTHON_DIR: "C:\\Python35"
#      PYTHON_VERSION: "3.5.x"
#      PYTHON_ARCH: "32"
#      BLOCK: "0"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON_DIR: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "64"
      BLOCK: "0"

# Disabled because done using azure-pipelines
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#      PYTHON_DIR: "C:\\Python37"
#      PYTHON_VERSION: "3.7.x"
#      PYTHON_ARCH: "32"
#      BLOCK: "0"
#
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#      PYTHON_DIR: "C:\\Python37-x64"
#      PYTHON_VERSION: "3.7.x"
#      PYTHON_ARCH: "64"
#      BLOCK: "0"

cache:
  - C:\\cmake-3.6.2

init:
  - python -m pip install -U scikit-ci scikit-ci-addons
  - python -m ci_addons --install ../addons

  - ps: ../addons/appveyor/rolling-build.ps1

install:
  - python -m ci install

build_script:
  - python -m ci build

test_script:
  - python -m ci test

after_test:
  - python -m ci after_test

on_finish:
  - ps: ../addons/appveyor/enable-worker-remote-access.ps1 -check_for_block

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\*

matrix:
  fast_finish: false

shallow_clone: false
