
initialize-venv: &initialize-venv
  name: Initialize Virtual Environment
  command: |
    python -m virtualenv ../venv || python -m venv ../venv
    . ../venv/bin/activate

ci-steps: &ci-steps
  steps:
    - checkout
    - run:
        <<: *initialize-venv
    - run:
        name: Install dependencies
        command: |
          . ../venv/bin/activate
          pip install -U scikit-ci scikit-ci-addons
          ci_addons --install ../addons
          ci install
    - run:
        name: Flake8
        command: |
          . ../venv/bin/activate
          ci before_build
    - run:
        name: Build
        command: |
          . ../venv/bin/activate
          ci build
    - run:
        name: Test
        command: |
          . ../venv/bin/activate
          ci test
    - run:
        name: Coverage
        command: |
          . ../venv/bin/activate
          ci after_test

version: 2
jobs:
  python27:
    docker:
      - image: circleci/python:2.7.15-stretch
    <<: *ci-steps
  python35:
    docker:
      - image: circleci/python:3.5.7-stretch
    <<: *ci-steps
  python36:
    docker:
      - image: circleci/python:3.6.8-stretch
    <<: *ci-steps
  python37:
    docker:
      - image: circleci/python:3.7.2-stretch
    <<: *ci-steps

workflows:
  version: 2
  test-package-publish:
    jobs:
      - python27
      - python35
      - python36
      - python37
